import requests, time, os

WANTED_CODE = os.getenv("VANITY_CODE")
WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK")
GUILD_ID = os.getenv("GUILD_ID")  # ايدي سيرفرك الأساسي عشان الزر يوديك له
DELAY = int(os.getenv("DELAY_SECONDS", 5))

def send_alert():
    """يرسل Embed + زر يوديك لصفحة الـ Vanity مباشرة"""
        vanity_settings_url = f"https://discord.com/channels/{GUILD_ID}/guild-settings/vanity-url"
            
                data = {
                        "content": "@everyone",
                                "embeds": [
                                            {
                                                            "title": "⚡ Vanity متاح الحين!",
                                                                            "description": f"**`discord.gg/{WANTED_CODE}`** فضى توه.\nاضغط الزر تحت عشان تروح تغيره بسرعة.",
                                                                                            "color": 3066993,  # لون أخضر
                                                                                                            "footer": {"text": "Vanity Notifier"},
                                                                                                                            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S.000Z", time.gmtime())
                                                                                                                                        }
                                                                                                                                                ],
                                                                                                                                                        "components": [
                                                                                                                                                                    {
                                                                                                                                                                                    "type": 1,  # Action Row
                                                                                                                                                                                                    "components": [
                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                "type": 2,  # Button
                                                                                                                                                                                                                                                                        "style": 5,  # Link style
                                                                                                                                                                                                                                                                                                "label": "غيّره الحين",
                                                                                                                                                                                                                                                                                                                        "url": vanity_settings_url,
                                                                                                                                                                                                                                                                                                                                                "emoji": {"name": "🚀"}
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                "username": "Vanity Sniper Alert"
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                        requests.post(WEBHOOK_URL, json=data)

                                                                                                                                                                                                                                                                                                                                                                                                                        # باقي الكود نفسه...
                                                                                                                                                                                                                                                                                                                                                                                                                        def is_code_free(code):
                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                    r = requests.get(f"https://discord.com/api/v10/invites/{code}", timeout=3)
                                                                                                                                                                                                                                                                                                                                                                                                                                            return r.status_code == 404
                                                                                                                                                                                                                                                                                                                                                                                                                                                except:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return False

                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"بديت أراقب discord.gg/{WANTED_CODE}...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                        sent = False
                                                                                                                                                                                                                                                                                                                                                                                                                                                        while True:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if is_code_free(WANTED_CODE) and not sent:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    send_alert()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sent = True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif not is_code_free(WANTED_CODE):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sent = False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    time.sleep(DELAY)